# Site settings
title: pixus.io
email: skorulis@pixus.io
description: > # this means to ignore newlines until "baseurl:"
  Pixus is a content sharing network built on top of webRTC

twitter_username: skorulis
github_username:  skorulis
timezone: Australia/Sydney

# Build settings
markdown: kramdown

